In [1]:
import numpy as np
# สร้างเมทริกซ์ 5*5 แบบสุ่ม
# หา Transpose matrix ของ A
# หา inversa matrix ของ A
# หา rank ของ A
# สร้างเมทริกซ์ขนาด 5*1 แบบสุ่ม
# หาคำตอบ x = A^-1*b
# หาค่าประมาณ b_hat = A*x
# หาว่าค่า b_hat มีค่าแตกต่างจาก b โดยใช้สูตร
# sum square error = sum(b- b_hat) ^2
# mean square error = ค่าเฉลี่ยของ sum square error
# root mean square error = รากที่สองของ mean square error

In [6]:
# สร้างเมทริกซ์ 5*5 แบบสุ่ม
A = np.random.randint(10,size=(5,5))
print(A)

[[2 3 8 0 8]
 [3 8 9 0 3]
 [6 5 9 2 2]
 [4 7 3 8 5]
 [6 7 1 8 7]]


In [7]:
# หา Transpose matrix ของ A
print(np.transpose(A))

[[2 3 6 4 6]
 [3 8 5 7 7]
 [8 9 9 3 1]
 [0 0 2 8 8]
 [8 3 2 5 7]]


In [20]:
# หา inversa matrix ของ A
np.linalg.inv(A)

array([[-0.05602716, -0.04244482,  0.15619694, -0.26825127,  0.22920204],
       [-0.08658744,  0.20713073, -0.12224109, -0.05093379,  0.08149406],
       [ 0.05772496, -0.05475382,  0.08149406,  0.15895586, -0.17932937],
       [ 0.01103565, -0.13179117,  0.04499151,  0.2895798 , -0.17582767],
       [ 0.11375212, -0.012309  , -0.07470289, -0.07279287,  0.09146859]])

In [24]:
# หา rank ของ A
np.linalg.matrix_rank(A)

5

In [22]:
# สร้างเมทริกซ์ขนาด 5*1 แบบสุ่ม
B = np.random.randint(10,size=(5,1))
print(B)

[[5]
 [4]
 [1]
 [4]
 [1]]


In [34]:
# หาคำตอบ x = A^-1*b
x = np.linalg.inv(A) * B
print(x)

[[-0.28013582 -0.21222411  0.78098472 -1.34125637  1.14601019]
 [-0.34634975  0.82852292 -0.48896435 -0.20373514  0.32597623]
 [ 0.05772496 -0.05475382  0.08149406  0.15895586 -0.17932937]
 [ 0.04414261 -0.52716469  0.17996604  1.15831919 -0.7033107 ]
 [ 0.11375212 -0.012309   -0.07470289 -0.07279287  0.09146859]]


In [40]:
# หาค่าประมาณ b_hat = A*x
b_hat = A*x
print(b_hat)

[[-0.56027165 -0.63667233  6.24787776 -0.          9.16808149]
 [-1.03904924  6.62818336 -4.40067912 -0.          0.97792869]
 [ 0.34634975 -0.2737691   0.73344652  0.31791171 -0.35865874]
 [ 0.17657046 -3.6901528   0.53989813  9.26655348 -3.51655348]
 [ 0.68251273 -0.08616299 -0.07470289 -0.58234295  0.64028014]]


In [43]:
# หาว่าค่า b_hat มีค่าแตกต่างจาก b โดยใช้สูตร
# sum square error = sum(b- b_hat) ^2
sum_square_error = sum(B - b_hat)**2
print(sum_square_error)

[236.97178608 170.5263511  142.90193156  35.97453761  65.43065753]


In [52]:
# mean square error = ค่าเฉลี่ยของ sum square error
mean_square_error = sum_square_error.mean()
print(mean_square_error)

130.36105277750553


In [53]:
# root mean square error = รากที่สองของ mean square error
root_square_error = np.math.sqrt(mean_square_error)
print(root_square_error)

11.417576484416713


In [85]:
C = np.random.rand(5,3)
Ct = C.transpose()
CtC = np.matmul(Ct,C)
CtC_inv = np.linalg.inv(CtC)
II = np.matmul(CtC_inv,CtC)
C_pinv = np.matmul(CtC_inv,Ct) # pseudo inverse matrix
# คำพยากรณ์
beta = np.matmul(C_pinv,C)
c_hat2 = np.matmul(C,beta)
# residual
error = C - c_hat2
error = error**2
error.sum().mean()

1.378195468203506e-30

In [88]:
#Cd = C[:,1] = C[:,-1]
Cd = C.copy()
print(C.shape)
print(np.linalg.matrix_rank(Cd))
Cd[:,-2] = 2*Cd[:,-1]
print(np.linalg.matrix_rank(Cd))

Cd_t = Cd.transpose()
Cd_tCd = np.matmul(Cd_t,Cd)
Cd_tCd_inv = np.linalg.inv(Cd_tCd)
Cd_pinv = np.matmul(Cd_tCd_inv,Cd_t)
beta2 = np.matmul(Cd_pinv,C)
c_hat_d2 = np.matmul(Cd_pinv,C)
print(C)
print(c_hat_d2)

(5, 3)
3
2
[[0.42061293 0.03052467 0.1831383 ]
 [0.89451609 0.37583894 0.56580007]
 [0.46097472 0.27279819 0.91436531]
 [0.61689638 0.55368653 0.2767655 ]
 [0.37136502 0.78065961 0.76007624]]
[[ 2.24750054e+16  1.87225781e+16  2.84327824e+16]
 [-1.22656922e+17 -7.19426835e+16 -9.86596364e+16]
 [ 2.45313844e+17  1.43885367e+17  1.97319273e+17]]


In [89]:
CdPinv = np.linalg.pinv(Cd)
beta_bdPinv = np.matmul(CdPinv,C)
c_hat_new = np.matmul(Cd,beta_bdPinv)
print(C)
print(c_hat_new)
error = ((C-c_hat_new)**2)
mse = error.mean()
print(mse)

[[0.42061293 0.03052467 0.1831383 ]
 [0.89451609 0.37583894 0.56580007]
 [0.46097472 0.27279819 0.91436531]
 [0.61689638 0.55368653 0.2767655 ]
 [0.37136502 0.78065961 0.76007624]]
[[0.42061293 0.19326092 0.1831383 ]
 [0.89451609 0.49039642 0.56580007]
 [0.46097472 0.53313163 0.91436531]
 [0.61689638 0.28712394 0.2767655 ]
 [0.37136502 0.4400564  0.76007624]]
0.01962974399694684


In [93]:
A = np.random.rand(5,5)
U,S,Vt = np.linalg.svd(A)
# U เป็นเมทริกซ์เชิงตั้งฉากที่มีคุณสมบัติ U^T x U = I
# V เป็น orthogonal matrix , V^Tx V = I
# S เป็น singular matrix ที่สมาชิกในแนวทแยง s11>s22>...srr 
# เรียก s11 เป็นค่า sigular values
UI = np.matmul(U.transpose(),U)
VI = np.matmul(Vt,Vt.transpose())
SS = np.diag(S)
SS

US = np.matmul(U,SS)
A_1 = np.matmul(US,Vt)
print(np.isclose(A,A_1))
print(A)
print(A_1)

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[[0.98698426 0.58854297 0.42839542 0.45973492 0.09929273]
 [0.45813072 0.97224749 0.20385884 0.35714011 0.45888507]
 [0.66126696 0.49881784 0.4758392  0.10171298 0.05450564]
 [0.99051451 0.65070543 0.39218825 0.3047918  0.35720163]
 [0.47481394 0.74616644 0.16456004 0.15592001 0.8304065 ]]
[[0.98698426 0.58854297 0.42839542 0.45973492 0.09929273]
 [0.45813072 0.97224749 0.20385884 0.35714011 0.45888507]
 [0.66126696 0.49881784 0.4758392  0.10171298 0.05450564]
 [0.99051451 0.65070543 0.39218825 0.3047918  0.35720163]
 [0.47481394 0.74616644 0.16456004 0.15592001 0.8304065 ]]


In [95]:
# Data Manipulation with Pandas
#conda install pandas
# การใช้ pandas
import pandas
print(pandas.__version__)

0.23.4


In [98]:
# หรือจใช้ชื่อย่อว่า pd
import pandas as pd

In [99]:
# Pandas Series เป็นอะเรย์หนึ่งมิติ เราสามารถสร้างได้จาก List หรือ array เช่น
data = pd.Series([0.25,0.5,0.75,1.0])
print(data)

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64


In [100]:
# การเข้าถึงผ่าน values
print(data.values)

[0.25 0.5  0.75 1.  ]


In [101]:
# อ่านต่าดัชนีตัวที่ 1,2 แต่ไม่รวม 3
print(data[1:3])

1    0.50
2    0.75
dtype: float64


In [105]:
# index ของสมาชิก ใช้
data.index[1]

'b'

In [106]:
# index อาจไม่จำเป็นต้องเป็นตัวเลขได้
data = pd.Series([0.25,0.5,0.75,1.0],
index = ['a','b','c','d'])

In [107]:
print(data.index)

Index(['a', 'b', 'c', 'd'], dtype='object')


In [108]:
print(data['a'])

0.25


In [122]:
for i in data.index:
    print(i,data[i])

a 0.25
b 0.5
c 0.75
d 1.0


In [131]:
population_dict = {'California': 38332521,
                  'Texas': 26448193,
                  'New York': 19651127,
                  'Florida': 19552860,
                  'Illinois': 12882135}
population = pd.Series(population_dict)
print(population)
print(population.index)

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64
Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')


In [132]:
for key in population.index:
    print(population[key])

38332521
26448193
19651127
19552860
12882135


In [138]:
print(population.keys().values)

['California' 'Texas' 'New York' 'Florida' 'Illinois']


In [140]:
# กรณีที่สร้างวัตถุจากคลาส
# pd.Series(data, index=index)
# data อาจเป็น list, นิพจน์ , dixtionary
# index เป็น list of index
score = pd.Series([1,2,3,7])
print(score)
print(score.index.values)

0    1
1    2
2    3
3    7
dtype: int64
[0 1 2 3]


In [142]:
# กำนหดให้มีค่าเดิมทุกตัว
ones = pd.Series(1,index=[0,1,2])
print(ones)
idx = np.arange(0,10)
print(idx)
ten_ones = pd.Series(1,index=idx)
print(ten_ones)

0    1
1    1
2    1
dtype: int64
[0 1 2 3 4 5 6 7 8 9]
0    1
1    1
2    1
3    1
4    1
5    1
6    1
7    1
8    1
9    1
dtype: int64


In [143]:
# create from dictionary
students = pd.Series({'Jphn': 40,'Alice': 50})
print(students)
three = pd.Series({2:'a',1:'b',3:'c'})
print(three)

Jphn     40
Alice    50
dtype: int64
2    a
1    b
3    c
dtype: object


In [144]:
area_dict = {'California': 423967,
            'Texas': 695662,
            'New York': 141297,
            'Florida': 170312,
            'Illinois': 149995}
area = pd.Series(area_dict)

In [145]:
state = pd.DataFrame({'population': population,
                     'area': area})

In [147]:
state

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [148]:
state.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [158]:
print(state.columns)
print(state.columns[0])
print(state.columns[1])

Index(['population', 'area'], dtype='object')
population
area


In [165]:
state.loc['California':'Florida']

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312

In [166]:
state['population']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: population, dtype: int64

In [171]:
state['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [168]:
state[['population','area']]

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [173]:
state[state.columns]

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [175]:
for e in state.columns:
    for c in state[e]:
        print(c)
    print('--------')

38332521
26448193
19651127
19552860
12882135
--------
423967
695662
141297
170312
149995
--------
