In [8]:
# abstract class
import abc
class AbstractAnimal(object):
    __metaclass__ = abc.ABCMeta
    
    @abc.abstractmethod
    def walk(self):
        ''' data '''
        
    @abc.abstractclassmethod
    def talk(self):
            ''' data '''

In [16]:
class Duck(AbstractAnimal):
    name = ""
    def __init__(self,newName):
        print("create a new duck")
        self.name = newName
    # overriden method
    def walk(self):
        print("The new duck walks.")
    def talk(self):
        print("Krup Krup!")

In [17]:
d = Duck("Donald")
d.walk()
d.talk()

create a new duck
The new duck walks.
Krup Krup!


In [18]:
class Dog(AbstractAnimal):
    name = ""
    def __init__(self,newName):
        print("create a new dog")
        self.name = newName
    # overriden method
    def walk(self):
        print("The new dog walks.")
    def talk(self):
        print("Hong Hong!")

In [21]:
dg = Dog("MooMee")
dg.walk()
dg.talk()

create a new dog
The new dog walks.
Hong Hong!


In [22]:
def testPolymophism(d):
    d.walk()
    d.talk()

In [23]:
a = Dog("Hi")
b = Duck("Slippy")
testPolymophism(a)
testPolymophism(b)

create a new dog
create a new duck
The new dog walks.
Hong Hong!
The new duck walks.
Krup Krup!


In [24]:
import numpy as np

In [25]:
x = np.float32(1.0)

In [30]:
x
print(type(x))

<class 'numpy.float32'>


In [31]:
y = np.int_([1,2,4])
k = y

In [33]:
y

array([1, 2, 4])

In [35]:
print(type(y))
k[0] = 7
print(y)
print(k[0])

<class 'numpy.ndarray'>
[7 2 4]
7


In [37]:
z = np.arange(3,dtype = np.uint8)

In [38]:
z

array([0, 1, 2], dtype=uint8)

In [39]:
z = np.arange(3,dtype = np.int8)

In [40]:
z

array([0, 1, 2], dtype=int8)

In [48]:
print(z.dtype)
print(z.size)
print(z.shape)
print(z.ndim)   # จำนวนคอลัมน์
print(z.T)      # data

int8
3
(3,)
1
[0 1 2]


In [49]:
L1 = list(range(1,9))
print(L1)
ab = [type(item) for item in L1]    # ใช้สรา้งลิสต์
print(type(ab))

[1, 2, 3, 4, 5, 6, 7, 8]
<class 'list'>


In [51]:
import array
L = list(range(10))
A = array.array('i',L)
A
# i is a type code indicating the contents are intrger.
print(type(A))

<class 'array.array'>


In [52]:
# array in Numpy
import numpy as np
# integer array
g = np.array([1,2,3,4,5,6])
print(type(g))
print(g)

<class 'numpy.ndarray'>
[1 2 3 4 5 6]


In [53]:
np.array([3.14, 4, 2, 5])

array([3.14, 4.  , 2.  , 5.  ])

In [54]:
# ระบุชนิดข้อมูลเองได้
np.array([1,2,3,4],dtype = 'float32')

array([1., 2., 3., 4.], dtype=float32)

In [68]:
# ลิสต์ซ้อนได้
t = np.array([range(1,1+3) for i in [2,4,6]])
print(t)
print(t.shape)
print(t.ndim)
print(t.size)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
(3, 3)
2
9


In [69]:
# อะเรย์ของจำนวนเต็มศูนย์ขนาด 5
x = np.zeros(5,dtype = int)
print(x)
print(type(x))
print(x.size)
print(x.shape)

[0 0 0 0 0]
<class 'numpy.ndarray'>
5
(5,)


In [70]:
y = np.zeros((5,2),dtype = int)
print(y)
print(type(y))
print(y.shape)
print(y.ndim)
print(y.size)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
<class 'numpy.ndarray'>
(5, 2)
2
10


In [71]:
o = np.zeros((2,3,4),dtype = int)
print(o)
print(o.shape)
print(o.ndim)
print(o.size)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
(2, 3, 4)
3
24


In [72]:
# อะเรย์ 3*5 filled with 1.2
np.full((3,5),1.2)

array([[1.2, 1.2, 1.2, 1.2, 1.2],
       [1.2, 1.2, 1.2, 1.2, 1.2],
       [1.2, 1.2, 1.2, 1.2, 1.2]])

In [74]:
# create an array filled with a linear sequence
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [83]:
# อะเรย์ของค่าที่อยู่ระหว่าง 0-1 จำนวน n = 10 ค่า
np.linspace(0,1,10)
radian = np.linspace(-np.pi,np.pi,20)
ar = np.array(radian)
print(ar)

[-3.14159265 -2.81089869 -2.48020473 -2.14951076 -1.8188168  -1.48812284
 -1.15742887 -0.82673491 -0.49604095 -0.16534698  0.16534698  0.49604095
  0.82673491  1.15742887  1.48812284  1.8188168   2.14951076  2.48020473
  2.81089869  3.14159265]


In [90]:
# การสุ่มตัวเลขแบบ uniform distribute
np.random.random((5,3))

array([[0.79916544, 0.68001994, 0.87788514],
       [0.85230217, 0.62010273, 0.47732867],
       [0.16670281, 0.17469642, 0.8603183 ],
       [0.32550393, 0.11625485, 0.42589076],
       [0.26740738, 0.28149405, 0.77619017]])

In [94]:
# การสุ่มตัวเลขแบบ normal distributed [-1,1]
# (b-a) * np.random.random_sample() + (a)
(1-(-1)) * np.random.random_sample((3,2)) - 1

array([[-0.77910979, -0.37481579],
       [-0.76779482,  0.6360685 ],
       [ 0.28700959, -0.02677415]])

In [96]:
# การสุ่มตัวเลขแบบ normal distributed value
np.random.normal(0,1,(4,3))

array([[ 1.88203985, -2.84939828,  0.44532452],
       [ 1.40884312,  0.07378641,  2.78008699],
       [-0.05597559,  1.08942249, -0.33851792],
       [ 1.10495256, -0.3506283 ,  0.62370041]])

In [97]:
# การสุ่มตัวเลขจำนวนเต็ม [0,9) แบบ 3x3
np.random.randint(0,10,(3,3))

array([[7, 1, 2],
       [4, 2, 4],
       [2, 7, 4]])

In [107]:
# เมทริกซ์เอกลักษณ์
I = np.eye(4)
A = np.random.random((4,4))
B = np.matmul(A,I)
print(I)
print(A)
print(B)
print(np.isclose(A,B))
print(np.diag(I))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.54348755 0.62857659 0.01783912 0.51419672]
 [0.42601295 0.68549217 0.09276356 0.92257688]
 [0.23096088 0.57298667 0.84409373 0.03223795]
 [0.65143453 0.33501972 0.31742565 0.7544288 ]]
[[0.54348755 0.62857659 0.01783912 0.51419672]
 [0.42601295 0.68549217 0.09276356 0.92257688]
 [0.23096088 0.57298667 0.84409373 0.03223795]
 [0.65143453 0.33501972 0.31742565 0.7544288 ]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[1. 1. 1. 1.]


In [108]:
# อะเรย์ที่ไม่ได้กำหนดค่าเริ่มต้น
# ค่าแล้วแต่ค่าที่มีอยู่ในหน่วยความจำ
A = np.empty(10)
B = np.empty((5,2))
print(A)
print(B)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[[            nan 0.00000000e+000]
 [3.85748907e-316 2.02369289e-320]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]


In [110]:
# Array Attributes
# ปล. ถ้า seed เดิมจะได้ตัวเลขชุดเดิม
import numpy as np
np.random.seed(0)    # seen for reproducibility
x1 = np.random.randint(10,size=6)    # One-dimensional array size=6
x1

array([5, 0, 3, 3, 7, 9])

In [112]:
x2 = np.random.randint(10,size=(4,3))    # Two-dimensional array size=(4,3)
x2

array([[3, 5, 2],
       [4, 7, 6],
       [8, 8, 1],
       [6, 7, 7]])

In [113]:
x3 = np.random.randint(10,size=(3,4,5))    # Three-dimensional array size=(3,4,5)
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [114]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[3 5]
 [4 7]]


In [116]:
x2_sub = x2[:2, :2].copy()
print(x2_sub)

[[3 5]
 [4 7]]


In [117]:
# Reshaping
grid = np.arange(1,10)
print(grid)
print(grid.shape)

[1 2 3 4 5 6 7 8 9]
(9,)


In [119]:
grid = grid.reshape(3,3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [125]:
x = np.array([1,2,3])
y = np.array([1,2,3])
print(x)
print(y)
z = np.concatenate([x,y])
print(z)
k = np.concatenate([x,y,[10,12,13]])
print(k)

[1 2 3]
[1 2 3]
[1 2 3 1 2 3]
[ 1  2  3  1  2  3 10 12 13]


In [126]:
grid = np.array([[1,2,3],[4,5,6]])
print(grid)
# เชื่อม 2 อะเรย์เข้าด้วยกัน
np.concatenate([[grid],[grid]])

[[1 2 3]
 [4 5 6]]


array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [129]:
x = np.array([1,2,3])
grid = np.array([[4,5,6],[7,8,9]])
print(x)
print(grid)

[1 2 3]
[[4 5 6]
 [7 8 9]]


In [130]:
# ต่อแถวใช้ vstack
x_new = np.vstack([grid,x])
print(x_new)

[[4 5 6]
 [7 8 9]
 [1 2 3]]


In [132]:
# 9่อคอลัมน์ใช้ hstack
c = np.array([[99,19]])
print(c)
y = np.hstack([[grid,c]])
print(y)
print(grid)

[[99 19]]
[array([[4, 5, 6],
       [7, 8, 9]]) array([[99, 19]])]
[[4 5 6]
 [7 8 9]]


In [141]:
# split of array
x = np.array([1,2,3,4,5,6,7,8,9,10,11])
y = np.split(x,2)
print(y)
print(y[0])

AttributeError: 'list' object has no attribute 'shape'

Signature: np.split(ary, indices_or_sections, axis=0)
Docstring:
Split an array into multiple sub-arrays.

Parameters
----------
ary : ndarray
    Array to be divided into sub-arrays.
indices_or_sections : int or 1-D array
    If `indices_or_sections` is an integer, N, the array will be divided
    into N equal arrays along `axis`.  If such a split is not possible,
    an error is raised.

    If `indices_or_sections` is a 1-D array of sorted integers, the entries
    indicate where along `axis` the array is split.  For example,
    ``[2, 3]`` would, for ``axis=0``, result in

      - ary[:2]
      - ary[2:3]
      - ary[3:]

    If an index exceeds the dimension of the array along `axis`,
    an empty sub-array is returned correspondingly.
axis : int, optional
    The axis along which to split, default is 0.

Returns
-------
sub-arrays : list of ndarrays
    A list of sub-arrays.

Raises
------
ValueError
    If `indices_or_sections` is given as an integer, but
    a split does not re