In [1]:
import numpy as np

In [6]:
k = np.random.rand(4,3)
k

array([[0.29697358, 0.10870476, 0.18203186],
       [0.58585849, 0.98175254, 0.95706877],
       [0.56987532, 0.96339402, 0.51189642],
       [0.28800538, 0.63747472, 0.7818591 ]])

In [45]:
np.random.normal(0,15,10)

array([-11.89661772,  -8.48654949,   1.66910599,  29.07384465,
        -3.53201477,  16.99960234, -11.4248294 , -13.6973875 ,
         8.6532244 ,  17.61410456])

In [46]:
np.linspace(-1,1,20)

array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])

In [86]:
A = np.random.rand(5,3)
A

array([[0.36062141, 0.73364274, 0.27034993],
       [0.64684646, 0.65289926, 0.11471968],
       [0.33051147, 0.27058452, 0.82323462],
       [0.83195295, 0.04525417, 0.32581352],
       [0.0874398 , 0.51545304, 0.29135719]])

In [87]:
B = np.random.rand(5,1)
B

array([[0.81873697],
       [0.47592982],
       [0.10874676],
       [0.26300808],
       [0.74859328]])

In [92]:
x = np.concatenate([A,B],axis=1)
x

array([[0.36062141, 0.73364274, 0.27034993, 0.81873697],
       [0.64684646, 0.65289926, 0.11471968, 0.47592982],
       [0.33051147, 0.27058452, 0.82323462, 0.10874676],
       [0.83195295, 0.04525417, 0.32581352, 0.26300808],
       [0.0874398 , 0.51545304, 0.29135719, 0.74859328]])

In [94]:
C = np.random.rand(2,4)
C

array([[0.67040263, 0.47524932, 0.64417047, 0.97235173],
       [0.94053402, 0.92989781, 0.08109857, 0.317612  ]])

In [104]:
y = np.concatenate([x,C])
y

array([[0.36062141, 0.73364274, 0.27034993, 0.81873697],
       [0.64684646, 0.65289926, 0.11471968, 0.47592982],
       [0.33051147, 0.27058452, 0.82323462, 0.10874676],
       [0.83195295, 0.04525417, 0.32581352, 0.26300808],
       [0.0874398 , 0.51545304, 0.29135719, 0.74859328],
       [0.67040263, 0.47524932, 0.64417047, 0.97235173],
       [0.94053402, 0.92989781, 0.08109857, 0.317612  ]])

In [108]:
a = [[1,2],[3,4]]
b = [[0,1],[5,6]]
ab = a+b
print(ab)
A = np.matrix(a)
B = np.matrix(b)
C = A+B
print(A)
print(B)
print(C)

[[1, 2], [3, 4], [0, 1], [5, 6]]
[[1 2]
 [3 4]]
[[0 1]
 [5 6]]
[[ 1  3]
 [ 8 10]]


In [114]:
X = np.random.randint(20,size=20)
print(X)
print(X.min())
print(X.max())
for i in X:
    Z = (i-X.min())/(X.max()-X.min())
    print(Z)

[14 13  8  7 17 10 16  5  0  6  6 12  3 12 11 16 14  4 18  0]
0
18
0.7777777777777778
0.7222222222222222
0.4444444444444444
0.3888888888888889
0.9444444444444444
0.5555555555555556
0.8888888888888888
0.2777777777777778
0.0
0.3333333333333333
0.3333333333333333
0.6666666666666666
0.16666666666666666
0.6666666666666666
0.6111111111111112
0.8888888888888888
0.7777777777777778
0.2222222222222222
1.0
0.0


In [125]:
x2 = np.random.randint(20,size=20)
print(x2)
numbers = []
for i in x2:
    if i%2 == 0:
        numbers.append(i)
print(numbers)

[ 4 17 16  1 11  4  0 17  9  1  1  5  4 16  7 16  2  4  7  8]
[4, 16, 4, 0, 4, 16, 16, 2, 4, 8]


In [197]:
A = np.random.random((3,3))
print(A)
B = np.sort(-A*-1)
print(B)
x = np.identity(3)
y = x/1*B
y

[[0.14145943 0.67143203 0.00506715]
 [0.22349308 0.5062819  0.7962221 ]
 [0.1837939  0.70316324 0.86614388]]
[[0.00506715 0.14145943 0.67143203]
 [0.22349308 0.5062819  0.7962221 ]
 [0.1837939  0.70316324 0.86614388]]


array([[0.00506715, 0.        , 0.        ],
       [0.        , 0.5062819 , 0.        ],
       [0.        , 0.        , 0.86614388]])

In [207]:
A = np.matrix(np.linspace(0,100))
print(A)
Y = np.matrix(142.323+40.029*A+np.exp(-0.00684*A))
print(Y)
CdPinv = np.linalg.pinv(A)
beta_bdPinv = np.matmul(CdPinv,Y)
print(beta_bdPinv)
print(A*beta_bdPinv)

[[  0.           2.04081633   4.08163265   6.12244898   8.16326531
   10.20408163  12.24489796  14.28571429  16.32653061  18.36734694
   20.40816327  22.44897959  24.48979592  26.53061224  28.57142857
   30.6122449   32.65306122  34.69387755  36.73469388  38.7755102
   40.81632653  42.85714286  44.89795918  46.93877551  48.97959184
   51.02040816  53.06122449  55.10204082  57.14285714  59.18367347
   61.2244898   63.26530612  65.30612245  67.34693878  69.3877551
   71.42857143  73.46938776  75.51020408  77.55102041  79.59183673
   81.63265306  83.67346939  85.71428571  87.75510204  89.79591837
   91.83673469  93.87755102  95.91836735  97.95918367 100.        ]]
[[ 143.323       225.00097453  306.67914122  388.3574974   470.03604046
   551.7147678   633.39367686  715.07276513  796.75203012  878.43146938
   960.11108049 1041.79086109 1123.4708088  1205.15092133 1286.83119638
  1368.51163169 1450.19222506 1531.87297429 1613.55387721 1695.2349317
  1776.91613565 1858.597487   1940.2789837 